const constants = {
	MOVIES_FETCHED: 'MOVIES_FETCHED',
	MOVIE_CREATED: 'MOVIE_CREATED',
	CLEAR_ALL_MOVIES: 'CLEAR_ALL_MOVIES',

	USER_LOGGED_IN: 'USER_LOGGED_IN',
	USER_LOGGED_OUT: 'USER_LOGGED_OUT'

}

export default constants;